### Spring properties
# Service registers under this name
spring:
#Configure Database
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/DosenMS
    username: dosen
    password: dosen
    driverClassName: org.postgresql.Driver

# HTTP Server (Tomcat) Port
server: 
  port: 2121
  